# Generated by Django 4.2.14 on 2024-10-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='imgevent',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
