# Generated by Django 4.2.14 on 2024-12-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0002_alter_schedules_dayshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='dayshow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_manager.dayshow'),
        ),
    ]
