# Generated by Django 4.2.14 on 2024-08-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0003_films_dayshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='dayshow',
        ),
        migrations.AddField(
            model_name='films',
            name='dayshow',
            field=models.ManyToManyField(blank=True, null=True, to='cinema_manager.dayshow'),
        ),
    ]
