# Generated by Django 4.2.14 on 2025-01-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0003_alter_schedules_dayshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayshow',
            name='status',
            field=models.CharField(choices=[('Có hiệu lực', 'valid'), ('Hết hạn', 'expire')], default='Có hiệu lực', max_length=100),
        ),
    ]
