# Generated by Django 4.2.14 on 2024-08-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0004_remove_films_dayshow_films_dayshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='day_show',
        ),
    ]
