# Generated by Django 4.2.14 on 2024-09-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0006_combodetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='bank_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
