# Generated by Django 4.2.14 on 2024-08-06 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0007_remove_films_dayshow_films_dayshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='dayshow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_manager.dayshow'),
        ),
    ]
