# Generated by Django 4.2.14 on 2024-09-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0008_schedules_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='bank_number',
        ),
    ]
