# Generated by Django 4.2.14 on 2024-08-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0008_schedules_dayshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
