# Generated by Django 4.2.14 on 2024-08-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0009_films_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
