# Generated by Django 4.2.14 on 2024-08-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0010_alter_seats_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
