# Generated by Django 4.2.14 on 2024-09-17 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0011_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_manager.bookings'),
        ),
    ]
