# Generated by Django 4.2.14 on 2024-08-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0011_alter_seats_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='film',
        ),
        migrations.AddField(
            model_name='schedules',
            name='film',
            field=models.ManyToManyField(blank=True, null=True, to='cinema_manager.films'),
        ),
    ]
