# Generated by Django 4.2.14 on 2024-09-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0012_alter_pay_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='bill',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
