# Generated by Django 4.2.14 on 2024-08-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0012_remove_schedules_film_schedules_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayshow',
            name='place',
        ),
        migrations.AddField(
            model_name='dayshow',
            name='place',
            field=models.ManyToManyField(blank=True, null=True, to='cinema_manager.place'),
        ),
    ]
