# Generated by Django 4.2.14 on 2024-08-07 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema_manager', '0013_remove_dayshow_place_dayshow_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('video', models.FileField(blank=True, null=True, upload_to='files/')),
                ('video_type', models.CharField(blank=True, max_length=20, null=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_manager.films')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
