# Generated by Django 4.2.14 on 2024-09-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0013_bill_qr_code_bill_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
