# Generated by Django 4.2.14 on 2024-09-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0014_alter_bill_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='confirm',
            field=models.CharField(blank=True, choices=[('Đã xác nhận', 'confirmed'), ('Chưa xác nhận', 'unconfirmed')], default='Đã xác nhận', max_length=255, null=True),
        ),
    ]
