# Generated by Django 4.2.14 on 2024-09-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0015_bill_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='confirm',
            field=models.CharField(blank=True, choices=[('Đã xác nhận', 'confirmed'), ('Chưa xác nhận', 'unconfirmed')], default='Chưa xác nhận', max_length=255, null=True),
        ),
    ]
