# Generated by Django 4.2.14 on 2024-09-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0016_alter_bill_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
