# Generated by Django 4.2.14 on 2024-08-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0016_service_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
