# Generated by Django 4.2.14 on 2024-08-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0017_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='view',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
