# Generated by Django 4.2.14 on 2024-09-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0017_contact_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='number_transaction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='status',
            field=models.CharField(choices=[('Now', 'now'), ('Coming', 'comming'), ('Stop', 'stop')], default='Now', max_length=100, null=True),
        ),
    ]
