# Generated by Django 4.2.14 on 2024-08-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0018_films_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='status',
            field=models.CharField(choices=[('Now', 'now'), ('Coming', 'comming')], default='Now', max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='schedules',
            name='film',
        ),
        migrations.AddField(
            model_name='schedules',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_manager.films'),
        ),
    ]
