# Generated by Django 4.2.14 on 2024-08-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0019_alter_films_status_remove_schedules_film_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
