# Generated by Django 4.2.14 on 2024-10-09 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0019_userquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_manager.films'),
        ),
    ]
