# Generated by Django 4.2.14 on 2024-10-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0020_alter_actors_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actors',
            name='film',
        ),
        migrations.AddField(
            model_name='actors',
            name='film',
            field=models.ManyToManyField(blank=True, null=True, to='cinema_manager.films'),
        ),
    ]
