# Generated by Django 4.2.14 on 2024-08-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0020_films_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='type',
            field=models.CharField(blank=True, choices=[('Regural', 'regural'), ('Vip', 'vip')], default='Regural', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='type',
            field=models.CharField(choices=[('Regural', 'regural'), ('Vip', 'vip')], default='Regural', max_length=100),
        ),
    ]
