# Generated by Django 4.2.14 on 2024-08-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0021_seats_type_alter_tickets_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
