# Generated by Django 4.2.14 on 2024-10-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0021_remove_actors_film_actors_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
