# Generated by Django 4.2.14 on 2024-10-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0022_alter_films_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='view',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
