# Generated by Django 4.2.14 on 2024-08-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0024_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='place',
            field=models.ManyToManyField(blank=True, null=True, to='cinema_manager.place'),
        ),
    ]
