# Generated by Django 4.2.14 on 2024-08-16 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0025_films_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_manager.place'),
        ),
    ]
