# Generated by Django 4.2.14 on 2024-08-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0029_alter_comments_film_alter_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='kind',
            field=models.CharField(blank=True, choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd'), ('E', 'e'), ('F', 'f'), ('G', 'g'), ('H', 'h'), ('I', 'i'), ('K', 'k'), ('L', 'l')], default='A', max_length=100, null=True),
        ),
    ]
